name: portfolio
description: "Odunayo Agboola Portfolio Website"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  google_fonts: ^8.0.2
  flutter_svg: ^2.2.4
  visibility_detector: ^0.4.0+2
  http: ^1.6.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
